In [1]:
print ("holla")

holla


In [2]:
mylist = ['hello', 'hola', 'bueno']

In [5]:
# Create a list
my_list = [5, 10, 15, 20, 25]

# 1. append(): Add an element to the end of the list
my_list.append(30)
print("After append: ", my_list)

# 2. insert(): Insert an item at a given position
my_list.insert(0, 0)
print("After insert: ", my_list)

# 3. extend(): Extend the list by appending elements from another list
my_list.extend([35, 40])
print("After extend: ", my_list)

# 4. remove(): Remove the first item from the list that has a value of x
my_list.remove(20)
print("After remove: ", my_list)

# 5. pop(): Remove and return the item at a given position, default is the last item
popped_item = my_list.pop()
print("After pop: ", my_list)
print("Popped item: ", popped_item)

# 6. index(): Return zero-based index in the list of the first item whose value is x
index = my_list.index(10)
print("Index of 10: ", index)

# 7. count(): Return the number of times x appears in the list
count = my_list.count(10)
print("Count of 10: ", count)

# 8. sort(): Sort the items in the list in ascending order
my_list.sort()
print("After sort: ", my_list)

# 9. reverse(): Reverse the elements of the list in place
my_list.reverse()
print("After reverse: ", my_list)

# 10. clear(): Remove all items from the list
my_list.clear()
print("After clear: ", my_list)


After append:  [5, 10, 15, 20, 25, 30]
After insert:  [0, 5, 10, 15, 20, 25, 30]
After extend:  [0, 5, 10, 15, 20, 25, 30, 35, 40]
After remove:  [0, 5, 10, 15, 25, 30, 35, 40]
After pop:  [0, 5, 10, 15, 25, 30, 35]
Popped item:  40
Index of 10:  2
Count of 10:  1
After sort:  [0, 5, 10, 15, 25, 30, 35]
After reverse:  [35, 30, 25, 15, 10, 5, 0]
After clear:  []


In [9]:
print(len(my_list))

5


In [8]:
my_list = [5, 10, 15, 20, 25]

In [2]:
numbers = list(range(0,30))
numbers

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29]

In [ ]:
new_list = []
for num in numbers:
    if len(new_list) >4:
        print(f'We have enough even numbers in new_list({len(new_list)}). break will top the loop for now')
        break
    elif num %2 == 0:
        new_list.append(num)
    elif num %2 != 0:
        
        continue
    print("I  never get excecuted")


In [1]:
list_of_numbers = list(range(0, 100))
list_of_odd_numbers_plus_ten = []


# use a for loop to create a list of odd numbers from the list of numbers from 0 to 100
# each time there is an odd number, add 10 to it and append it to the list_of_odd_numbers_plus_ten
# stop adding numbers to the list when there are 35 numbers
# use break and continue statements in your code
for number in list_of_numbers:
    if number % 2 != 0:
        list_of_odd_numbers_plus_ten.append(number+10)
    if len(list_of_odd_numbers_plus_ten) == 35:
        break
    else:
#         print(number%2)
        continue
        
print (list_of_odd_numbers_plus_ten)
    # Continue writing code here

[11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79]


In [3]:
numbers = list(range(0, 30))
new_list = []

for num in numbers:
    if len(new_list) >= 0:
        print(f'We have enough even numbers in new_list ({len(new_list)}). break will stop the for loop now')
        break
        
    elif num % 2 == 0:
        new_list.append(num)
    elif num % 2 != 0:
        continue
        print('i never get executed')
    print(num, 'is even.')
    print('this does not print for odd numbers\nbecause the continue statement skips\nthe code that follows in the for loop\nand goes straight back to the next element in the for loop')

    
print("I broke from the list! I'm out of the loop")   

We have enough even numbers in new_list (0). break will stop the for loop now
I broke from the list! I'm out of the loop


In [9]:
i = 0

while i < 10:
    if i == 0:
        # print ("Breaking out")
        break
    elif i % 2 == 0:
        print ("This is an even number", i)
        i += 1
        continue
        print ("hola")
    print (i)
    i+= 1
else: print('Loop complete')


print("I am outside the loop")   # outside the loop

I am outside the loop


In [10]:
i =0 
while i <6:
    i +=1
    if i==3:
        continue
    print (i)

1
2
4
5
6


In [2]:
import os 
print(os.listdir())

['.git', '.ipynb_checkpoints', 'recap notebbok.ipynb']


In [7]:
def calculations():
    num1 = int(input("Enter number 1"))
    num2 = int(input("Enter number 2"))
    print (f"The sum is {num1+num2}, product is {num1*num2}, difference is {num1-num2}, and quotient is {num1/num2}")

calculations()

The sum is 40, product is 400, difference is 0, and quotient is 1.0


In [25]:
# Write a function named print_squared_divisible_by_n(numbers) that takes

# Takes a user input of n
# Creates a list of numbers that run from 1 to numbers.
# The function should iterate over the numbers, square each number, and print the squared values that are divisible by n.


def print_squared_divisible_by_n(numbers):
    n = int(input("Enter value of n"))
    my_list = list(range(1,numbers+1))
    for item in my_list:
        if ((item**2)%n) == 0:
            print(item**2)


In [27]:
print_squared_divisible_by_n(10)

9
36
81


In [31]:
import numpy as np
myarr = np.array(range(1,11))
print(myarr)

[ 1  2  3  4  5  6  7  8  9 10]


In [32]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [18]:
time_for_breakfast = 1468
cooked_pancakes = 1
total_pancakes = 5
cook_time_per_pancake = 27
flipping_time = 5
time_per_pancake = (cook_time_per_pancake * 2) + (flipping_time * 3 )


while cooked_pancakes <= total_pancakes and time_for_breakfast >= time_per_pancake:
    print (f"Cooking pancake{cooked_pancakes}")
    time_for_breakfast -= time_per_pancake
    
    # print (f"current pancake{cooked_pancakes}, current time{time_for_breakfast}")
    cooked_pancakes += 1

print("Agnes has {} seconds left to eat her pancakes.".format(time_for_breakfast))

Cooking pancake1
Cooking pancake2
Cooking pancake3
Cooking pancake4
Cooking pancake5
Agnes has 1123 seconds left to eat her pancakes.


In [1]:
evil_monster = "Bowser"

def princess_peachs_castle():
    print(f"{evil_monster} is trying to kidnap Princess Peach!")

In [2]:
princess_peachs_castle()

Bowser is trying to kidnap Princess Peach!


In [29]:
capitalized_destinations = ['argentina', 'mexico', 'italy', 'finland', 'canada', 'croatia']
# define function here
def capitalize_countries():
    capitalized_names = []
    for name in capitalized_destinations:
        capitalized_names.append(name.title())
    # print(capitalized_names)
    return capitalized_names

In [30]:
capitalize_countries()

['Argentina', 'Mexico', 'Italy', 'Finland', 'Canada', 'Croatia']

In [34]:
def meet(traveller): 
                              # "sally"
    welcome_message = "Hi " + traveller.title() + ", I'm so glad we'll be going on the trip together!"
    print(welcome_message)
    return welcome_message

In [35]:
capitalized_destinations = ['argentina', 'mexico', 'italy', 'finland', 'canada', 'croatia']

for traveller in capitalized_destinations:
    meet(traveller)

Hi Argentina, I'm so glad we'll be going on the trip together!
Hi Mexico, I'm so glad we'll be going on the trip together!
Hi Italy, I'm so glad we'll be going on the trip together!
Hi Finland, I'm so glad we'll be going on the trip together!
Hi Canada, I'm so glad we'll be going on the trip together!
Hi Croatia, I'm so glad we'll be going on the trip together!


In [ ]:
dict_keys(['categories', 'coordinates',
            'display_phone', 'distance', 'id', 'image_url',
              'is_closed', 'location', 'name', 'phone',
            'price', 'rating', 'review_count', 'transactions', 'url'])

In [1]:
students_scores = {
    "John": [85, 90, 92],
    "Emily": [78, 82, 80],
    "Michael": [92, 88, 94],
    "Sarah": [76, 80, 85]
}

In [12]:
for key, value in students_scores.items():

    print ('Name: ' + key  )
    print (*value, sep = '\n')
    # print (' '.join(value))

    # name = key 
    # aver = sum(list(value))/len(list(value))
    
    # print (key, 'kk', aver)

Name: John
85
90
92
Name: Emily
78
82
80
Name: Michael
92
88
94
Name: Sarah
76
80
85


In [15]:
# Question: You are a teacher and need to calculate the average score for each student in a class. You have a dictionary where each key represents a student's name, and the value is a list of their scores. How would you use a loop to calculate and print the average score for each student?
students_scores = {
    "John": [85, 90, 92],
    "Emily": [78, 82, 80],
    "Michael": [92, 88, 94],
    "Sarah": [76, 80, 85]
}

In [16]:
len(students_scores)

4

In [17]:
from scipy import stats

<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject


KeyboardInterrupt: 

In [1]:
import numpy as np

In [2]:
list = list (range(0,11))
list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [3]:
arr = np.array(list)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
type(arr)

numpy.ndarray

In [5]:
#addition:
np.add(arr, 10)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [6]:
#subtraction
np.subtract(arr, 10)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [10]:
np.power(arr,0)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [12]:
np.divide(arr,10)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [14]:
newarr = np.divide(arr,5)
newarr

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [15]:
np.ceil(newarr)

array([0., 1., 1., 1., 1., 1., 2., 2., 2., 2., 2.])

In [17]:
np.floor(newarr)

array([0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 2.])

In [18]:
np.round(newarr)

array([0., 0., 0., 1., 1., 1., 1., 1., 2., 2., 2.])

In [20]:
np.array_equal(arr,newarr)

False

In [23]:
print(arr)
print (newarr)
np.multiply(arr, newarr)

[ 0  1  2  3  4  5  6  7  8  9 10]
[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2. ]


array([ 0. ,  0.2,  0.8,  1.8,  3.2,  5. ,  7.2,  9.8, 12.8, 16.2, 20. ])